### ISSUE TITLE
Retrieving Folder Children

### ISSUE THREAD

**Issue by Eltik** [qgustavor/mega#100]
Hello! I am attempting to use NodeJS to retrieve files from an external Mega.nz folder (ex. this [link](https://mega.nz/#F!6qpXzAoT!AKE2joqJwedoTRqjJMTXsQ)), however when utilizing `mega.file(url).children` I get "undefined" returned. I've also tried `.decrypt(key)`, but nothing happens when using the method. No errors; just nothing happening.

**Describe the bug**
Essentially, handling folders does not seem to work. I can't access the folder's children, nor am I able to "decrypt" and pipe files locally.

**To Reproduce**
Using NodeJS v17.7.2 and ExpressJS. The below code is called upon the user accessing the web server online.
```js
let lnFile = mega.file(url).loadAttributes(function(err, file) {
    if (err) {
        console.log(err)
    } else {
        console.log(file.name); // Returns correctly
        console.log("Size: " + file.size); // Returns correctly
    }
});
console.log(lnFile.children); // Returns undefined
```
Also tried:
```js
let lnFile = mega.file(url);
let key = lnFile.key;
console.log(lnFile.directory); // Returns true
await mega.decrypt(key).pipe(fs.createWriteStream("../../web_server/ln/" + lnFile.name)); // Nothing happens, no file is written.
```

**Expected behavior**
I expected `lnFile.children` to return an array of files, but it returns undefined even though the mega.nz link is valid. I also expected `mega.decrypt` to pipe a file to the directory I provided.

**Additional context**
The mega.nz link leads to a folder of files, not a file itself.

**Comment by qgustavor** [comment]
If I understood right I think you're just having trouble to understand async execution:

In your first example you call `console.log(lnFile.children);` outside the callback, so it's called before the library had time to load the attributes, that's why it's `undefined`. If you call it inside the function it will work.

In your second example you found that `lnFile.directory` is true, that's because this info don't need to be loaded from the network, neither the file key, those info are already present in the URL, unlike the information about the file children.

I don't know how you are handling asynchronous execution in your code: there are callbacks, which is when you pass a function that is run after the function finished, which is what you did in your first example, and there is async/await, which you tried to use in your second example.

To be fair, your second example is kinda a mess: is like if you tried experimenting with the library in a REPL without reading the documentation. The `.decrypt` function will not help you, it's a low level function that almost no one uses that still exists in the library to keep it backyards compatible with older versions. Your code don't do what you expect because it don't do what you expect: `.decrypt` is not a download function, is a decryption function, `.children` is only set after you load attributes (and wait for those attributes to be loaded).

Here is a example on how to integrate this library with Express:

```javascript
const { File } = require('megajs')
const express = require('express')
const app = express()
const port = 3000

app.get('/', async (req, res) => {
  const megaUrl = req.query.url
  if (!megaUrl) return res.send('Pass a MEGA url via ?url=')

  let rootFile
  try {
    rootFile = File.fromURL(megaUrl)
  } catch (e) {
    return res.send('Invalid URL: ' + e)
  }

  // Loading the file from loadAttributes is needed to support files in shared folders
  const linkedFile = await rootFile.loadAttributes()
  res.attachment(linkedFile.name)
  linkedFile.download().pipe(res)
})

app.listen(port, () => {
  console.log(`Example app listening on port ${port}`)
})
```

In the above example async/await is used: you put async before starting the function to mark that this function will use await, and use await before loadAttributes to mark that the execution needs to wait for loadAttributes before continuing.

**Comment by Eltik** [comment]
It’s not that the documentation is unclear it’s just that I didn’t read it carefully haha. I’ll also look into some JS tutorials. I taught the lang myself and didn’t learn it properly, thanks again for your help and sorry for wasting your time.
