### ISSUE TITLE
Automate releasing workflow to be sure to publish the correctly built files

### ISSUE THREAD

**Issue by i0x0** [qgustavor/mega#118]
![Screenshot_20220903_113407](https://user-images.githubusercontent.com/29006605/188277706-1226b0bb-0bbd-4a85-90c6-5b874b1711c8.png)

**Comment by qgustavor** [comment]
That's true. I need to migrate the current publishing workflow to something more straightforward, probably this: https://pr-release.org/

I will publish 1.0.8 right now. Leave this issue open, it will keep track the migration to pr-release.

**Comment by qgustavor** [comment]
I'll keep this issue open until [this](https://github.com/orgs/community/discussions/13836) or [this](https://github.com/orgs/community/discussions/21999) get sorted soon. Since npm is already famous for its supply chain attacks and since it's recommended to always use latest pr-release while providing it [a way too broad token](https://github.com/JAForbes/pr-release/issues/274) I think pr-release can wait a while.

Maybe I can implement a simpler CI workflow [like this one](https://github.com/qgustavor/ass-parser/blob/b6845a13e6fa13f050152c19fee8f89b307904c6/.github/workflows/npm-publish.yml) in the meanwhile.

**Comment by qgustavor** [comment]
[GitHub now supports fine-grained personal access tokens](https://github.blog/changelog/2022-10-18-introducing-fine-grained-personal-access-tokens). Looks like [there are plans for npm supporting it too](https://github.com/github/roadmap/issues/557). As soon both supports I will implement pr-release without having to worry too much about potential supply chain attacks.

**Comment by qgustavor** [comment]
Granular access tokens [are finally available in npm](https://docs.npmjs.com/creating-and-viewing-access-tokens#creating-granular-access-tokens-on-the-website). Now it's possible to use pr-release quite safely. I'll work on that.

**Comment by qgustavor** [comment]
I just finished implementing pr-release. I hope everything went well.
