### ISSUE TITLE
API not working. Uncaught Error: ENOENT (-9): Object (typically, node or user) not found. Wrong password?

### ISSUE THREAD

**Issue by TjeerdvanDijk** [qgustavor/mega#128]
Hello, Im trying to get this api to work but I just can't login. I tried everything described in the tutorial but it is simply not working.

I tried the following code:

      import { Storage } from 'https://cdn.skypack.dev/megajs@1'

      const storage = new Storage({
        email: 'Emailhere',
        password: 'passwordhere',
        userAgent: null
      })

it gives me this error:
![image](https://user-images.githubusercontent.com/44869554/201522534-321b8646-1dfd-482d-8851-6a901fa2dbe7.png)

**Comment by hernandiazz9** [comment]
I had the same problem, I have 2 mega accounts, one is working, the other one have the same problem. I'm thinking that maybe is some mega config on account? not sure but I will keep looking for the problem.

**Comment by qgustavor** [comment]
I'll look into it when it happens to my account since I'm not willing to ask anyone to share an account that's being affected and I don't anyone to do that. If someone is getting affected by this issue and want to debug try logging-in by the web client and check the API calls using developer tools, maybe there was some change in the login flow.

Other option is checking MEGA's code, they made their source-code available here: https://github.com/meganz/webclient/ The thing is: their code and commits are kinda hard to understand, last time I had to check it (IIRC for implementing V2 account support) they implemented a feature in a single commit changing dozens of files at the same time so it took some time until I found the relevant files.

**Comment by qgustavor** [comment]
I found an issue with the browser build: for V1 accounts (a.k.a. old accounts) it don't correct hashes passwords with lengths that are not multiple of 4 characters. MEGA's old hashing scheme is a bit... messy. 

I released a fix [in this pull request](https://github.com/qgustavor/mega/pull/132), you can test it using [this pre-release version](https://www.npmjs.com/package/megajs/v/1.1.1-next.2). A stable release will take some time since having issues with pr-release (sometimes it never finishes running).

Can you test that pre-release and check if it solves the issue?
