### ISSUE TITLE
Throws an error at the login moment 

### ISSUE THREAD

**Issue by CursedMun** [qgustavor/mega#152]
**Describe the bug**

**To Reproduce**

Run this code in Node 18.11
"megajs": "^1.1.2",

```js
import { Storage } from 'megajs'
  const storage = new Storage({
    email: env.MEGA_EMAIL,
    password: env.MEGA_PASSWORD,
  })
  
  await storage.ready
  const folder = File.fromURL(
    'any url'
  )

  await folder.loadAttributes()
```

**Expected behavior**
to give me the folders structure

**Additional context**
happens on `await storage.ready` maybe because I have `@` in the passowrd
```
megajs/dist/main.node-cjs.js:289
  return buffer.toString("base64").replace(/\+/g, "-").replace(/\//g, "_").replace(/=/g, "");
                ^

TypeError: Cannot read properties of undefined (reading 'toString')
    at e64 (node_modules/megajs/dist/main.node-cjs.js:289:17)
    at node_modules/megajs/dist/main.node-cjs.js:2150:36
    at Array.forEach (<anonymous>)
    at node_modules/megajs/dist/main.node-cjs.js:2142:18
    at node_modules/megajs/dist/main.node-cjs.js:104:27
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.11.0
```

**Comment by qgustavor** [comment]
https://github.com/qgustavor/mega/discussions/138

**Comment by qgustavor** [comment]
I should add something: probably @CursedMun created the [fixedmegajs](https://www.npmjs.com/package/fixedmegajs) npm package to fix this issue, but some things:

- They did not edited anything in the readme explaining what was "fixed", so I had to use a code diff to find the fix.
- The fork source-code was not published which... in fairness, it's allowed by the license... but making the fork source-code open then submitting a PR would be better: it's not like this library is no longer supported, I just don't want to babysit people that can't read the f* documentation.
- This issue was fixed in a later version, so anyone using their library (which is probably just they) is missing other fixes from newer versions and newer features.
