### ISSUE TITLE
Listing Files in Folder Not Working (v1.3.3)

### ISSUE THREAD

**Issue by EvanTrow** [qgustavor/mega#226]
**Describe the bug**
Listing file in a folder link returns an empty children array. 

**To Reproduce**

Run this code in Node 20.11.1 with a folder link. 

```ts
async function getMegaFiles(megaLink: MegaLink): Promise<MegaFile[]> {
	let files: MegaFile[] = [];

	console.log('Getting mega files:', megaLink);

	const root = File.fromURL(megaLink.url);
	const key = root.key;
	await root.loadAttributes();
	root.key = key;
}
```

**Expected behavior**
With folder link that has children it should list them out. 

**Additional context**
This was working before today.

**Comment by oddwizard** [comment]
Rolling back, the issue seems to also existent in v1.3.2. Last working version seems to be v1.3.1.

Root cause seems to be pull #224 somewhere overriding `File#children` with `[]` when/after calling `File#loadAttributes()`.

The 3times reappearing `if (this.directory) this.children = []` seems to be an illogical check to me and probably should have been `if (this.children) ...`; as this would also be consistent with other if-checks in #224.

Can someone check this and pull? I lack testing capabilities.

**Comment by qgustavor** [comment]
I just saw your issue. I disabled notifications for this repository since I'm quite overwhelmed at the moment, but I look into that later. In the meanwhile, I hope someone sends a pull request.

**Comment by qgustavor** [comment]
The issue from #224 is that there were directories without a  `.children` property, so the check should be `this.directory`. I will just add a check to not override an existing `.children` property.

**Comment by qgustavor** [comment]
Can you check this? https://github.com/qgustavor/mega/pull/230
