### ISSUE TITLE
Names of directories are null

### ISSUE THREAD

**Issue by Fromclaszureme** [qgustavor/mega#35]
Hello
Each directory (true) name is null, except Cloud Drive, Rubbish bin and Inbox;
This feature were supported by tonistiigi's mega

**Comment by qgustavor** [comment]
I just tested here and listing files in accounts is working:

```javascript
const mega = require('megajs')
const storage = mega({
  email: process.env.TEST_ACCOUNT,
  password: process.env.TEST_PASSWORD
}, error => {
  if (error) return console.log('error', error)
  console.log(storage.root.children.map(e => e.name)) // > returns the list of node names
})
```

**Comment by Fromclaszureme** [comment]
![screenshot](https://user-images.githubusercontent.com/6378162/34463921-bf34a602-ee7c-11e7-91b6-a56c9a1c0790.jpg)
what about folders? they are null :[

**Comment by qgustavor** [comment]
The name of nodes (which can be folders or files) are stored in a encrypted
JSON object.

Possibility 1: the client which created or last renamed those don't stored
the filename in the object. Test it in other clients (including
tonistiigi's) and tell me the results.

Possibility 2: the structure of the JSON object changed and my test account
works because the folders on it are in the old format. In this case I need
to get the new object structure or a working implantation code then adapt
the code to handle this.

Possibility 3: there's a unhandled decryption error. If I remember well
some clients (like old versions of the official client) can encrypt data in
a not usual way. Because handling is a bit hacky I removed code that
handles it. I'm on my phone now so I can't check code now.

**Comment by Fromclaszureme** [comment]
I test some other test accounts, looks like some of Folders are named and some of them are not - on the left side forked mega; on right - unforked
![screenshot2](https://user-images.githubusercontent.com/6378162/34464697-b9e9c8a6-ee9c-11e7-9201-64222b163b9e.jpg)

same account(previous) via unforked mega
![screenshot3](https://user-images.githubusercontent.com/6378162/34464698-d267f416-ee9c-11e7-812b-e1b986e7bb98.jpg)

**Comment by qgustavor** [comment]
Seems the only possibility is that there's a decryption error. Get the raw attribute JSON object by replacing that console.log line from the first example with `console.log(storage.root.children.map(e => e.this.attributes))` It must not be null, otherwise there's a decryption error.

If possible you can also clone the repository, `npm install`, edit the library code then `npm run build` and test it to check if's working. Edit it adding error handling [here](https://github.com/qgustavor/mega/blob/3daa01b355c311c81d386a3f7be73ceeb9d3bd22/lib/storage.js#L137) by replacing `() => {}` with `err => this.emit('error', err)`.

Strange: there is more error handling code [in the forked code](https://github.com/qgustavor/mega/blob/3daa01b355c311c81d386a3f7be73ceeb9d3bd22/lib/file.js#L320-L331) than in [in the original code](https://github.com/tonistiigi/mega/blob/eb2c8fc639ee7affb3c3d4811bad200c7d4d8a92/lib/file.js#L52-L63).

**Comment by qgustavor** [comment]
What are the results? Was it really a unhandled decryption error or it's other issue?

Also, how to handle errors when files have corrupted attributes? For now I think it's best to don't list the file and emit an event signalizing that a file was corrupted (but how to name it? 'file-decrypt-error'?). Emitting an error on Storage (like above) can break working code.

**Comment by Fromclaszureme** [comment]
Sorry for delay, i have built a git version - names are still null and attributes are undefined; left megajs, right unforked mega
![default](https://user-images.githubusercontent.com/6378162/34568935-5a4bf4c6-f178-11e7-98b5-4f3b2cd64fdc.png)

not sure that, just skip corrupted files is good idea (:
This error happens only with folders, files are good and, sometimes, forked code show files, that unforked doesn't

**Comment by qgustavor** [comment]
As it returned undefined then there's a problem when decrypting.

Try restoring the behavior of the old library (just copy the old `unpackAttributes` code into the new library). I changed [the null byte handling](https://github.com/qgustavor/mega/commit/c80526d2c8a35808952632d6cd1adf992c9d9f60#diff-17dc9a452db5488b5cc544f82988d51bL219) to match [the original webclient implementation](https://github.com/meganz/webclient/blob/87b95c419400269963261cf80ddf77d38101445c/nodedec.js#L620-L622).

I also added that string replace to remove any kind of garbage after the JSON object. This "garbage removal" part isn't part of the original webclient, try removing it.
