### ISSUE TITLE
Uploads not completing

### ISSUE THREAD

**Issue by konnextv** [qgustavor/mega#43]
Both this and the CLI version don't complete uploads for most files. No error, the process seems to be waiting for a complete event that never fires.
The only file I could upload was a small .js file.
I suppose MEGA did some changes to their API - does anyone here have an idea how to solve this?

Thanks in advance!

**Comment by qgustavor** [comment]
I'm also having this problem since this month. I used a sniffer to check what's wrong and MEGA servers aren't returning file identifiers ("hashes") when uploading. I tried to emulate a browser (changing headers and user agent) and it still not worked. Using HTTPS don't fixed the issue. I don't know what's wrong.

**Comment by qgustavor** [comment]
Checking [megatools recent updates](https://github.com/megous/megatools/commits/master/lib/mega.c) seems [we need to retry upload on errors](https://github.com/megous/megatools/commit/a6df742506d8e266ebabf02007b7ce34638928d6#diff-3ccbd28b349aa24a94a45e8d348c81ac). But seems the server don't return any error. It needs more testing.

**Comment by qgustavor** [comment]
Fixing #13 can solve this: maybe MEGA servers now have a max chunk limit when uploading. Or they're enforcing checksums, which can be implemented [like this](https://github.com/megous/megatools/commit/5d9fa4be389448aea6b80e5c745640f16959b260#diff-3ccbd28b349aa24a94a45e8d348c81ac).

**Comment by qgustavor** [comment]
Fixing #13 can solve this: maybe MEGA servers now have a max chunk limit when uploading. Or they're enforcing checksums, which can be implemented [like this](https://github.com/megous/megatools/commit/5d9fa4be389448aea6b80e5c745640f16959b260#diff-3ccbd28b349aa24a94a45e8d348c81ac).

*Edit:* by the way I don't have too much free time but you can send a pull request fixing this.

**Comment by konnextv** [comment]
> by the way I don't have too much free time but you can send a pull request fixing this.

I am looking into this right now but I am not able to build the repo (my only experience with modules is _using_ them D:) - can you possibly assist me with this? If yes, please email me at hi (at) konnextv (dot) eu to not spam this :)

**Comment by qgustavor** [comment]
1. Clone the repository and dir into it
1. `npm install`
1. Edit the source at /lib; upload code [is here](https://github.com/qgustavor/mega/blob/6039e2de4bba66d2636eae0b225259abd759faae/lib/mutable-file.js#L103-L331)
1. Test using `npm test` (it don't tests upload because issue #32, but tests other things which can break)
1. Build the library using `npm run build`
1. Test uploading (`request('./dist/main.node-cjs.js')` then use the library as usual)
1. Commit and send a pull request if it fixes the issue

**Comment by qgustavor** [comment]
*Seems I will have to fix this issue myself...*
