### ISSUE TITLE
Support new MEGA accounts

### ISSUE THREAD

**Issue by ed-miller** [qgustavor/mega#46]
Hi, 
when I use my old Mega Accounts and login with this API, it works fine.

When I create a new Mega Accounts and try to login with this API, error coming: 
  EEXPIRED (-8): The upload target URL you are trying to access has expired. Please request a fresh one.

It seems that new accounts using another type of login?

**Comment by qgustavor** [comment]
https://github.com/megous/megatools/issues/411

Temporary fix: create an account using megareg.

I already expected changes in the login code because the old code is a bit
messed (multiple rounds of AES-ECB as key derivation and non-standard RSA
to authenticate). What I don't expected are they breaking third party
clients.

I will check what was changed. On megatools issue seems no one explained in
detail what changed.

**Comment by megous** [comment]
People from megatools like your analysis of the changes. :) And it looks like that sans two factor auth, at least the login flow in megatools could be made compatible with the new API, without too many changes, and without any UI changes.

I suspect that the registration flow also changed, so that will probably not be supported in megatools anytime soon.

**Comment by qgustavor** [comment]
MegaApiClient (written in C#) supports new accounts since [this commit](https://github.com/gpailler/MegaApiClient/commit/247644819aca235ad6a212b37f0276e87926ecf8#diff-4b906dc0dc82621c074d8ed6f2808cc1). It was quite simple to implement.

I think MEGA will allow changing iteration count in future. It's quite simple to implement: just add this value to the "us0" request response on login and store iteration count when signing up or changing passwords. It will allow users make their accounts more secure at the spent of taking more time to login.

@megous Registration flow changed. Most changes [are here](https://github.com/meganz/webclient/commit/a2786d490244348b57fa2b5c0696194620f809e3#diff-ccaa6daacc88b548c8cfcdda119cf81eR494). Other change in a later commit is that passwords with white spaces in the start or end are not allowed when signing up ([here](https://github.com/meganz/webclient/commit/43675e04db1a27bdc6c6d0d7c236aedcad38d0ff#diff-ccaa6daacc88b548c8cfcdda119cf81eR41)).

I'm not in a hurry to implement those changes on mega-js as megareg is still working. I don't know for how long it will keep working: MEGA might just drop support for V1 registration flow because it's "less secure".

**Comment by qgustavor** [comment]
*For some reason I fell fixing this was easier than I expected...*
