### ISSUE TITLE
Problem to upload File to specific Folder

### ISSUE THREAD

**Issue by siftmash** [qgustavor/mega#52]
First I create folder (mkdir) in return I gate MutableFile = NEWFOLDER

 fs.createReadStream(filePath + '\\' + fileName).pipe(NEWFOLDER.upload(fileName));

file was uploaded to root not to NEWFOLDER

**Comment by qgustavor** [comment]
I just wrote a test case to check this: 22912242feee18c6f0693b0ac57cdfc43dccfb35 As you can see [here](https://travis-ci.org/qgustavor/mega/jobs/622858247#L269) this test failed.

Instead of using the folder handler as the upload target it used `0`. This bug must be [here](https://github.com/qgustavor/mega/blob/547eabbafebb9c97dfeee5341ae1ed015e84a911/lib/mutable-file.js#L193). But this `0` in fact comes from [here](https://github.com/qgustavor/mega/blob/547eabbafebb9c97dfeee5341ae1ed015e84a911/lib/mutable-file.js#L180) so either I wrote the test case wrong or the MEGA mocking server implementation is wrong.

I will try to test using the real MEGA server later. In the meanwhile try using the target argument like this:

```javascript
someReadStream.pipe(folder.upload({name: fileName, target: folder}))
```

**Comment by siftmash** [comment]
:( Unfortunately it does not work

**Comment by qgustavor** [comment]
I updated the test cases [here](https://github.com/qgustavor/mega/commit/5c8a2bbb78bf46c3baa42f60f3e2d11cdf12e4b7). As you can see [here](https://travis-ci.org/qgustavor/mega/jobs/622867473) tests are now passing.

I tested the mocking server aggressively when testing a large application which uses this library before connecting it with real servers, so I think the mock implementation is quite similar with the real servers (at least when dealing with features that megajs supports).

Can you write a test case where it fails? You can also debug the code using some debugger or temporally edit the library code in node_modules to check whats the value of `result` [here](https://github.com/qgustavor/mega/blob/547eabbafebb9c97dfeee5341ae1ed015e84a911/lib/mutable-file.js#L191-L195). It should be the same handler as the folder you created, not the one from root folder.

**Comment by siftmash** [comment]
Everything is fine my bug, when recursively creating folders
