### ISSUE TITLE
allow get milliseconds of file

### ISSUE THREAD

**Issue by bluelovers** [qgustavor/mega#65]
it will easy use `Data.now() - file.milliseconds`

**Comment by qgustavor** [comment]
Currently `file.timestamp` [is taken directly](https://github.com/qgustavor/mega/blob/170cbd7181a83ee3ab5d71308b580932a2378968/lib/file.js#L40) from `file.ts` returned by the server. Sure, as JavaScript often uses milliseconds I think that would be better if it returned the timestamp in milliseconds, but [since the beginning](https://github.com/tonistiigi/mega/blob/eb2c8fc639ee7affb3c3d4811bad200c7d4d8a92/lib/file.js#L18) it worked this way.

Anyway it's simple to convert: just do `Data.now() - file.timestamp * 1000`. If you think it's not ideal for you use case then send a pull request adding `this.timestampMs = this.timestamp * 1000` right after [this line](https://github.com/tonistiigi/mega/blob/eb2c8fc639ee7affb3c3d4811bad200c7d4d8a92/lib/file.js#L18) (`timestampMs` because it's similar to [Node's FS module](https://nodejs.org/api/fs.html#fs_class_fs_stats)).

P.S.: `Date.now()` returns time in milliseconds (10<sup>-3</sup> second), not microsecond (10<sup>-6</sup> second).

**Comment by qgustavor** [comment]
Fixed by #67.
