### ISSUE TITLE
Add a check for definition

### ISSUE THREAD

**Issue by muhammadamir-github** [qgustavor/mega#80]
A check is needed at https://github.com/qgustavor/mega/blob/a627db06be2d6d88ebac99906ee4340bc3a339d2/lib/api.js#L104 for resp before checking resp.w, resp.sn or resp.a, resp is sometimes undefined which crashes the app.

**Comment by qgustavor** [comment]
The `if (err) throw err` can crash the app too. [Since 2018](https://github.com/qgustavor/mega/issues/47#issuecomment-446959330) that issues caused by show the API module handles errors were been noticed.

I don't know how to handle those errors. In fact, I still don't understand this module well, most of it is just [tonistiigi's code](https://github.com/tonistiigi/mega/blob/master/lib/api.js) rewritten to use modern JavaScript (like classes instead of prototypes). Also there was a change when I rewrote: the original code logged errors to the console, which polluted the console, so I rewrote to throw the error instead of logging... which caused some issues.

Fell free to fix those issues with a pull request.

**Comment by amirparvez** [comment]
I think a param, abort/throw,  should be accepted while creating a new storage according to which errors must be handled. Abort should return false and cancel the http request. I haven't went through all the code, i might make this change in future. Let me know if you can think of anything better.

**Comment by qgustavor** [comment]
Can you check if this issue persists in 1.0?

**Comment by qgustavor** [comment]
Closing issue since there was no response and looks like this issue was already fixed.
