### ISSUE TITLE
No login storage

### ISSUE THREAD

**Issue by jonra1993** [qgustavor/mega#82]
I am trying to use this lib to have access to my mega files, but when I try to log in I also get null. Also I received and warning email from Mega. Please can you help to know what I am doing wrong?

const options = {email: 'xxxxxx@hotmail.com', password: 'xxxxx'}
const storage = new mega.Storage({email: 'hz-hertzio@hotmail.com', password: 'Asterisco123', autologin: false})
await storage.login((result)=>{
  console.log('result', result)
})

**Comment by qgustavor** [comment]
You're trying to use promises, this library use callbacks (because it was created before promises were a huge thing). The first argument from callbacks is the error, which in your case is null as there is no error.

Well, I don't know why you're creating an options object and not using it. You don't need to use `autologin: false` unless you need to change something related to the connection (like setting up a proxy). Some basic example:

```javascript
const { Storage } = require('megajs')
const storage = new Storage({
  email: process.env.MEGA_EMAIL,
  password: process.env.MEGA_PASSWORD
})
storage.on('ready', () => {
  // do something with storage, like...
  storage.upload('hello world.txt', 'hello world', error => {
    if (error) return console.error(error)
    console.log('the file was uploaded')
  })
})
```

Check [the storage test case for more examples](https://github.com/qgustavor/mega/blob/a627db06be2d6d88ebac99906ee4340bc3a339d2/test/storage.test.js#L31-L35) (it uses `autologin: false` to change the default gateway with the testing one, but in most cases it's not needed), [megajs-cli code](https://github.com/qgustavor/megajs-cli/blob/fc403011a6e8ab9dbd7bcb1cd3e1282ea8cd6afc/lib/login-handler.js#L41-L57) (it also uses `autologin: false`, but to set up a proxy).

Notice that [there are plans to rewrite this library using promises and TypeScript](https://github.com/qgustavor/mega/issues/64). Would be great if you can contribute in some way.

**Comment by jonra1993** [comment]
Hello, @qgustavor thanks for your comments. Upgrade the in sounds awesome I have some experience with Typescript which is the plan to start rewriting?
