### ISSUE TITLE
function detectSize is causing memory leak

### ISSUE THREAD

**Issue by Karmel0x** [qgustavor/mega#84]
this function is causing memory leak
https://github.com/qgustavor/mega/blob/a627db06be2d6d88ebac99906ee4340bc3a339d2/lib/util.js#L45 https://github.com/qgustavor/mega/blob/a627db06be2d6d88ebac99906ee4340bc3a339d2/lib/mutable-file.js#L255

my case: uploading many huge files, just one after the other

passing `size` option to `upload` function resolves the problem, as it's not using this function then

**Comment by qgustavor** [comment]
That's a functionality [from tonistiigi's mega](https://github.com/tonistiigi/mega/blob/eb2c8fc639ee7affb3c3d4811bad200c7d4d8a92/lib/storage.js#L343-L348). When I converted tonistiigi's library into ES6 I remember to have noticed that [the way this function works](https://github.com/tonistiigi/mega/blob/eb2c8fc639ee7affb3c3d4811bad200c7d4d8a92/lib/util.js#L47-L58) is not that great, as it puts everything in memory. I can't disable this functionality without breaking compatibility, the solution, as you said, is just specifying the size.  [Documentation for this function says](https://github.com/qgustavor/mega/wiki/MutableFile#uploadoptions--name-data-callback): "Note that because MEGA's API needs final data length before uploading can start, streaming only fully works if you specify the size of your data. Otherwise it needs to first buffer your data to determine the size"

Even if this pitfall is documented, it's pretty easy to forget it: even [megajs-cli](https://github.com/qgustavor/megajs-cli/blob/fc403011a6e8ab9dbd7bcb1cd3e1282ea8cd6afc/lib/commands/upload.js#L85-L89) have this issue (and I think I never noticed it because I hardly ever upload large files).

I think that is not ideal changing the library to remove options that would break backyards compatibility now, as there is a plan to rewrite the library, even if it will take a long time as I'm not planning to do it alone without community feedback, mostly because I don't know what streaming pattern to use: there are Node streams, W3C Streams API and Async Generators, each one with advantages and drawbacks.

I hope that in the rewrite those pitfalls get removed, like disallowing uploading without specifying a size first and disallowing specifying encryption keys (which is pretty bad as there was a famous Mega client using a constant all zeroes key on uploads instead of using safety random generated keys, making Mega security worse for those who use this client and for those who download files uploaded using this client).
